const POKEMON_LIST_REQUEST = 'POKEMON_LIST_REQUEST';
const POKEMON_LIST_SUCCESS = 'POKEMON_LIST_SUCCESS';
const POKEMON_LIST_FAILURE = 'POKEMON_LIST_FAILURE';


const types = {
    POKEMON_LIST_FAILURE,
    POKEMON_LIST_REQUEST,
    POKEMON_LIST_SUCCESS
}

export default types;