const POKEMON_LIST_REQUEST = 'POKEMON_LIST_REQUEST';
const POKEMON_LIST_SUCCESS = 'POKEMON_LIST_SUCCESS';
const POKEMON_LIST_FAILURE = 'POKEMON_LIST_FAILURE';

const POKEMON_REQUEST = 'POKEMON_REQUEST';
const POKEMON_SUCCESS = 'POKEMON_SUCCESS';
const POKEMON_FAILURE = 'POKEMON_FAILURE';

const POKEMON_MOVES_REQUEST = 'POKEMON_MOVES_REQUEST';
const POKEMON_MOVES_SUCCESS = 'POKEMON_MOVES_SUCCESS';
const POKEMON_MOVES_FAILURE = 'POKEMON_MOVES_FAILURE';

const POKEMON_CHANGE_QUERY = 'POKEMON_CHANGE_QUERY';


const types = {
    POKEMON_LIST_REQUEST,
    POKEMON_LIST_SUCCESS,
    POKEMON_LIST_FAILURE,
    
    POKEMON_REQUEST,
    POKEMON_SUCCESS,
    POKEMON_FAILURE,


    POKEMON_MOVES_REQUEST,
    POKEMON_MOVES_SUCCESS,
    POKEMON_MOVES_FAILURE,
    
    POKEMON_CHANGE_QUERY,
}

export default types;