const CONNECTION_INIT = 'CONNECTION_INIT';
const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS';
const CONNECTION_FAIL = 'CONNECTION_FAIL';
const CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED';

const types = {
    CONNECTION_INIT,
    CONNECTION_SUCCESS,
    CONNECTION_FAIL,
    CHAT_MESSAGE_RECEIVED,
}

export default types;