const CONNECTION_INIT = 'CONNECTION_INIT';
const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS';
const CONNECTION_FAIL = 'CONNECTION_FAIL';
const CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED';
const CHAT_MESSAGE_SENT = 'CHAT_MESSAGE_SENT';

const MOVE_RECEIVED = 'MOVE_RECEIVED';
const MOVE_SENT = 'MOVE_SENT';
const ENEMY_POKEMON_RECEIVED = 'ENEMY_POKEMON_RECEIVED';



const types = {
    CONNECTION_INIT,
    CONNECTION_SUCCESS,
    CONNECTION_FAIL,
    CHAT_MESSAGE_RECEIVED,
    CHAT_MESSAGE_SENT,

    MOVE_RECEIVED,
    MOVE_SENT,

    ENEMY_POKEMON_RECEIVED
}

export default types;